### ISSUE TITLE
Payload creation error in MariaDB when trying to Upload an Shell

### ISSUE THREAD

**Issue by Shazgul** [ron190/jsql-injection#10066]
`[12:46:20,520] Payload creation error: com.jsql.model.exception.JSqlException: Payload integrity verification failed: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '\'\'),1,60),floor(rand(0)*2))from information_schema.tables group by 2)a)--' at line 1`

Any Solutions?

**Comment by ron190** [comment]
Maybe a server side protection, the empty string `\'\'` inside the server response seems weird.
You can use the Network tab to check the payload URL syntax and the HTTP response code, or send me more information privately for further verifications.
