### ISSUE TITLE
Issues displaying full screen

### ISSUE THREAD

**Issue by Snipercatz** [ron190/jsql-injection#1731]
I'm having an issue getting the GUI to appear properly.  I've tried changing the different windows options in my GTK tweak tool, but there's no difference.  I don't experience this issue with any other app or what not.  Suggestions? 
![screenshot from 2016-02-29 20 05 15](https://cloud.githubusercontent.com/assets/8577656/13416465/17ae3d48-df20-11e5-9348-b527f7e7f9b8.png)

**Comment by ron190** [comment]
Use [jsql-injection](https://github.com/ron190/jsql-injection).
