### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by Snipercatz** [ron190/jsql-injection#1732]
Sorry if I'm missing something but I can't figure out how to install this.  I've read the 'readmes" and what not, and looked through all the folders for an install, configure, make file....Sorry if I'm overlooking the obvious....

**Comment by ron190** [comment]
Install [java](http://java.com) if you didn't have already.

Then download the [latest jSQL executable .jar](https://github.com/ron190/jsql-injection/releases) and double click on it to open the main window (or you may type in a terminal: java -jar jsql-injection-vxxx.jar, or right click on file, choose "Open with..." and select "Java(TM) Platform SE binary").
