### ISSUE TITLE
Tamper space

### ISSUE THREAD

**Issue by italy2010** [ron190/jsql-injection#2]
Hello seem jsql cannot load db information . my target is vulernable with union based.

02:05:00 jSQL Injection version 0.6
02:05:12 Starting new injection
02:05:12 Connection test...
02:05:16 Get insertion character...
02:05:18 Time based test...
02:05:34 Read error Read timed out
02:05:34 Read error Read timed out
02:05:34 Read error Read timed out
02:05:34 Read error Read timed out
02:05:50 Read error Read timed out
02:05:50 Read error Read timed out
02:05:57 Blind test...
02:06:20 Error based test...
02:06:23 Normal test...
02:06:31 Using normal injection...
02:07:00 Fetching informations...
02:07:04 Fetching databases...
02:07:09 Fetching fails: no data to parse for null
02:08:14 Starting new injection
02:08:14 Connection test...
02:08:17 Get insertion character...
02:08:19 Time based test...
02:08:31 Blind test...
02:08:52 Error based test...
02:08:56 Normal test...
02:09:24 Execution stopped.
02:09:37 Starting new injection
02:09:37 Connection test...
02:09:40 Get insertion character...
02:09:42 Time based test...
02:09:58 Read error Read timed out
02:09:58 Read error Read timed out
02:09:58 Read error Read timed out
02:09:58 Read error Read timed out
02:10:22 Blind test...
02:10:37 Error based test...
02:10:40 Normal test...
02:10:48 Using normal injection...
02:11:16 Fetching informations...
02:11:19 Fetching databases...
02:11:23 Fetching fails: no data to parse for null

**Comment by ron190** [comment]
Can you provide more info on the pb by mail or pastebin ? Alternatively you may test with jsql alpha v0.6.

**Comment by italy2010** [comment]
plz give me your mail address.

**Comment by ron190** [comment]
ron190 [at] ymail [dot] com

**Comment by italy2010** [comment]
please check your email.

**Comment by ron190** [comment]
Problem comes from SQL commentary string '--' at the end of injection chain, for example in 

    param=1+UNION+SELECT+1,2,3--
sqlmap just appends '--', jSQL appends '--+' which is not accepted everytime:

    param=1+UNION+SELECT+1,2,3--+
I'll add tamper to test both. Thank you for the report.
