### ISSUE TITLE
not found admin page

### ISSUE THREAD

**Issue by BosSLtd** [ron190/jsql-injection#4062]
hi, why the above version 0.6 can not find the admin page?

[<a href='https://postimg.org/image/ccemg9mnl/' target='_blank'><img src='https://s32.postimg.org/tcxioxzp1/found_admin.png' border='0' alt='found admin'/><br />](url)

version 0.75
[<a href='https://postimg.org/image/qmmaypfbl/' target='_blank'><img src='https://s32.postimg.org/o5ajrfvf9/not_found_admin.png' border='0' alt='not found admin'/><br />](url)

thank you

**Comment by ron190** [comment]
I don't see a reason for this failure, the code didn't change much since v0.6.
Can you contact me privately with a pastebin or a message by mail with further details ?

**Comment by ron190** [comment]
You can find something interesting from the http response code in the Network tab. 
Can you check if the pages "voice/admin" and "voice/index.php" are responding "404 Not Found" in the new version ?

**Comment by BosSLtd** [comment]
jsql-injection-alpha.v0.6
[<a href='https://postimg.org/image/b0gq787jr/' target='_blank'><img src='https://s31.postimg.org/laj56gxff/yes.png' border='0' alt='yes'/><br />](url)
jsql-injection-v0.75
[<a href='https://postimg.org/image/5l8yw3vdj/' target='_blank'><img src='https://s31.postimg.org/ddzmo31cr/image.png' border='0' alt='no'/><br />](url)

**Comment by ron190** [comment]
I guess the option "Follow HTTP redirection" is unchecked and results in the failure. I think I will ignore the option during the search of admin pages or alert the user in some way.
I will close your issue when I'll had figure out something enough clear and explicit for the user.

![jsql-admin-page](https://s32.postimg.org/4zl8nso11/Untitled.png)

**Comment by BosSLtd** [comment]
thanks for the answer

**Comment by ron190** [comment]
jSQL was very restrictive and responses `3xx Redirection` were ignored when `Follow redirection` was unchecked :
```java
return responseCodeHTTP.indexOf("200 OK") >= 0;
```
I changed the test to accept both 2xx Success and 3xx Redirection regardless of  `Follow redirection` :
```java
return responseCodeHTTP.matches(".+[23]\\d\\d.+");
```
This will be integrated in the next version.
Many thanks for the report!
