### ISSUE TITLE
Saving the dump?

### ISSUE THREAD

**Issue by radiaku** [ron190/jsql-injection#47006]
Hello, Can we save the dump? Tried to copy to excel but not working...

**Comment by ron190** [comment]
If copy/paste does not work you can save a dump from menubar, menu File and Save Tab As... Menubar is displayed with alt key or Advanced arrow on the top right. 
You can also drag/drop the content of a table in Notepad++ or Excel.

Copy/paste works for me though on Win7 with Java 8 and jsql v0.79.

**Comment by mrizkihidayat66** [comment]
Can't it dump whole dumped data into .sql or .sqlite3 file?

**Comment by ron190** [comment]
@mrizkihidayat66 I'm not familiar with any use case requiring to create a new database from the dump, usually dump is just for manual review with text or csv.
Let me know if you think about any use case I'm missing.
