### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Szrzvdny** [ron190/jsql-injection#53579]
First thank you for developing this project。
Can you add a tamper module similar to sqlmap?
Because in the penetration test will inevitably encounter some waf, conventional sql statement will be used to intercept。
So it can increase their bypass waf sql attack statement just fine。

**Comment by ron190** [comment]
You're welcome, I think about implementing Tamper and WAF [for ages](https://github.com/ron190/jsql-injection/projects/4#card-4290574).

Until I add Tamper to the tool, you can open the SQL Engine and manually edit the SQL query model if you know what is activating the WAF.

For example if I know that the word `GROUP` is banned by a WAF, I can adapt the query and change the syntax to bypass the WAF:

![image](https://user-images.githubusercontent.com/1971480/30081092-251347b0-9286-11e7-8c7d-cb00cf437856.png)

I think I'll be able to start the Tamper and WAF tasks soon, I have just finished a feature to test each parameters and it was a pain :) :

![image](https://user-images.githubusercontent.com/1971480/30080757-0f4af500-9285-11e7-9a27-05b0f3820b21.png)

**Comment by Szrzvdny** [comment]
I've seen what you said SQL Engine
but I found that for a novice, it is not easy to modify the statement
for example：
![image](https://user-images.githubusercontent.com/24920385/30081957-aa961388-92bb-11e7-9210-8cb7bbbf33e3.png)
I do not know how to change it；
It's more difficult for me。
Also, I found some places there are some garbled.
![image](https://user-images.githubusercontent.com/24920385/30082047-ff9c6a80-92bb-11e7-9d1c-41cd6cdc0234.png)
I do not know if it is my problem.

**Comment by Szrzvdny** [comment]
Forget to say，getting a shell seems a bit of a problem
![image](https://user-images.githubusercontent.com/24920385/30083135-eb5d90cc-92bf-11e7-9980-4dc308850104.png)
Can be seen, he has been implemented through the php file,but it does not seem to be echoed
Get a sqlshell is the same.
![image](https://user-images.githubusercontent.com/24920385/30083340-acd1d628-92c0-11e7-80a2-d7b690b02a76.png)
At first I thought it was my local environment, but I found sqlmap can return sql-shell.
I do not know if it is my problem.
Again, I do not know if this is my local environment.
If so, please allow me to say sorry。

**Comment by ron190** [comment]
Yes, it's normal with current release v0.79, it will be fixed in next one v0.80, like in the screenshot:

![image](https://user-images.githubusercontent.com/1971480/30085160-8d1e070a-9295-11e7-8fb0-3d5dd32263da.png)

And I agree, SQL Engine is for advanced users. Common users will rather need a Tamper panel to choose SQL alterations more easily.

I think I'll add a new category in Preferences to select the desired Tamper scripts with a bunch of checkboxes, I'll work on it in the coming days.

**Comment by Szrzvdny** [comment]
Ok, look forward to your update。
Can I focus on your Twitter or facebook?
Although the language barrier a little trouble.

**Comment by ron190** [comment]
Regarding the problem with shells, what I see on the screenshots:
- Host URL is `http://127.0.0.1/Less-1/?id=1`,
- Shell URL is `http://127.0.0.1/.0.79.jw.php`, the part `Less-1/` is not used.

So the folder `Less-1/` can be a virtual directory or there is a URL rewriting from `http://127.0.0.1/Less-1/` to `http://127.0.0.1/`.

You can add `http://127.0.0.1/` to the field `[Optional] URL to the shell directory` and retry:

![image](https://user-images.githubusercontent.com/1971480/30086076-ab9262e0-9299-11e7-9966-b9de2ed92f2e.png)

I'll figure a way to check automatically each parts of the orginal URL to find the shell.

**Comment by ron190** [comment]
Sure, @ron190jsql on Twitter

**Comment by Szrzvdny** [comment]
![image](https://user-images.githubusercontent.com/24920385/30086435-a2c42d22-92cd-11e7-99a1-558534ff4b05.png)
Ok, have solved this problem, I found that this is my negligence, no careful observation, in the network can see him is visiting ```http://127.0.0.1/Less-1/.0.79.jw.php,```
I apologize for my carelessness
But I wondered why I need to do that.
Can not let him automatically go to visit ```http://127.0.0.1/.0.79.jw.php/```

**Comment by ron190** [comment]
You're right, I'll see to check if the shells get a response from each part of the URL, so it won't require any user action.

**Comment by Szrzvdny** [comment]
ok,I have no problem now。

**Comment by ron190** [comment]
I've released version v0.80 to fix several things including translations and shell creations.

Also I'm wondering which Chinese font to use instead of Monospace.
Monospace seems correct on Windows but blurry on Linux, I've tried Ubuntu Regular too and it's pretty good.

Is there any official Chinese font already shipped on both Windows and Linux which displays characters decently ?

**Comment by ron190** [comment]
Switched anyway to Ubuntu Regular.
