### ISSUE TITLE
update impossible

### ISSUE THREAD

**Issue by Ghostboy-287** [ron190/jsql-injection#6450]
hello
i have kali rolling latest version, and i tried to update the jsql-injection tool but i had this messages:

Checking updates...
An error occured while checking updates, download the latest version from official website :
https://github.com/ron190/jsql-injection/releases

How to resolve it, or how to install it correctely when i ll download it like .jar file  (which folder have i to put it on)

thank you

**Comment by ron190** [comment]
First you need to download the latest binary from Github, it's currently the file jsql-injection-v0.77.jar and you can find it on the release page [https://github.com/ron190/jsql-injection/releases](https://github.com/ron190/jsql-injection/releases).

Then you place the .jar on your desktop and you launch it directly from here with a double-click or with command `java -jar jsql-injection-v0.77.jar`.

If you want to replace the one used by Kali then you need to place the file in `/usr/share/jsql/` and rename it into `jsql-injection.jar`. Then Kali should open the new version when you will type `jsql`.

If you don't want to replace the original file then modify the one named `jsql`, it's a text file, and replace command `java -jar jsql-injection.jar` into `java -jar jsql-injection-v0.77.jar` in the source :

```
#!/bin/bash
cd /usr/share/jsql/ && java -jar jsql-injection.jar "$@"
```
