### ISSUE TITLE
I got mistake

### ISSUE THREAD

**Issue by JackandBlackLLL** [ron190/jsql-injection#65247]
When i run jsql on mac os i got mistake

[22:35:45,427] Проверка подключения
[22:35:45,826] Connection failed: ﻿https
[22:35:46,329] Scan finished

pls help me

**Comment by JackandBlackLLL** [comment]
And when i use batch scanning time to time scan stoped

**Comment by ron190** [comment]
I have just tested https connection using Scan on Mac OS without issue.
Can you check the URL for mistakes or test injection directly in the address bar?

Also if scan stops without any error message then maybe it's a bug, you can confirm that by opening the Java tab using menubar Windows>Show Panel and checking for Exception messages in this tab.
