### ISSUE TITLE
small font in screen resolution of 4K

### ISSUE THREAD

**Issue by xo10** [ron190/jsql-injection#68970]
Hi,

Great too!

but can you update me how to make the font larger for the screen resolution of 4K? (everything goes small)

thanks

**Comment by ron190** [comment]
Thanks, it seems that the Java display size depends entirely on the Desktop size, not on the application.

You can try to just check option [Override high DPI scaling behavior](https://superuser.com/a/1207925) or [Disable display scaling on high DPI settings](https://stackoverflow.com/a/35178577/2073804).

**Comment by xo10** [comment]
many thanks man, what about GNU/Linux?

I used in some apps the option to increase the font then the app comes OK!

**Comment by ron190** [comment]
Yes, you're right.

There seems to be several workaround:
- Easiest: just use Java 9,
- Or on Java 6 you can use `-Dsun.java2d.dpiaware=false` to start the program, so run `java -Dsun.java2d.dpiaware=false -jar jsql-injection-v0.81.jar`,
- Also I can implement a switch to upscale every fonts in the GUI.

If you have a screenshot I'm just curious to see how they added this to this app.

**Comment by xo10** [comment]
Attached the screenshot that you asked!
![1](https://user-images.githubusercontent.com/35911698/37250337-44c99ede-250b-11e8-929c-e8d105aa50fe.png)

**Comment by ron190** [comment]
Thanks, indeed, so tiny.

If you fixed the problem using Java 9 or using the Java 6 tricks then let us know !

**Comment by xo10** [comment]
I tried with java -Dsun.java2d.dpiaware=false -jar jsql-injection-v0.81.jar

but, still so tiny

**Comment by ron190** [comment]
Yes, I see on the screenshot that you are running jSQL on Java 8 (1.8.0_161).

You can just download Java 6 or 9 in addition to Java 8 to fix this.

**Comment by ron190** [comment]
I was running the older Java 9-ea (Early Access) without any problem, but now I can reproduce the error with Java 9.0.4 too.

It seems that Oracle is planning to remove JAXB with Java 11 so it's currently hidden in Java 9.0.4.

You can try to run `java --add-modules java.xml.bind -jar jsql-injection-v0.81.jar` to enable the hidden package.

I will try to fix this in the next release.

**Comment by ron190** [comment]
Yes it's working with `--add-modules java.xml.bind`.

I have added the corresponding [task](https://github.com/ron190/jsql-injection/projects/8#card-8425869).

**Comment by xo10** [comment]
I've run: java --add-modules java.xml.bind -jar jsql-injection-v0.81.jar


**But still so tiny nothing happened!**


![1](https://user-images.githubusercontent.com/35911698/37903949-932f34f0-3102-11e8-8949-b00433f6a4ec.png)

**Comment by xo10** [comment]
Many thanks, now i can see the font clearly.

Please, in next update put the font size & dark theme in the options.

Thanks again!

**Comment by ron190** [comment]
I have created the corresponding tasks in the project page for [dark theme](https://github.com/ron190/jsql-injection/projects/1#card-8589489), [JDK9 compatibility](https://github.com/ron190/jsql-injection/projects/8#card-8425869) and [4k support](https://github.com/ron190/jsql-injection/projects/1#card-8537498).

Here is a sample of [Darcula theme](https://github.com/bulenkov/Darcula) from Konstantin Bulenkov already used with IntelliJ and Netbeans and roughly applied here on jSQL:

![image](https://user-images.githubusercontent.com/1971480/38162537-04fb0f94-34e3-11e8-80a2-0679ad9129af.png)

Actually a lot of things are not working properly with this theme, like bottom splitpanel stops working, some borders and colors are wrong, but maybe someday I'll manage to fix it.

**Comment by xo10** [comment]
Take your time for the next update.

you are the best!
