### ISSUE TITLE
Jsql Kali 2018 problem

### ISSUE THREAD

**Issue by 5l1v3r1** [ron190/jsql-injection#70695]
Hello,

As far as i know kali starts to support jdk9 as default. Because of that everytime i try to run jsql it gives me this error:

18:04:40,984 ERROR root:34 - Unhandled Exception on main
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.jsql.model.injection.vendor.Vendor.<clinit>(Vendor.java:6)
	at com.jsql.model.InjectionModel.<init>(InjectionModel.java:113)
	at com.jsql.MainApplication.main(MainApplication.java:57)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 3 more

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "main"

Can you please add jdk9 support or can you please define how to use it with jdk8 support on jdk9 default ?
Thank you very much for attention.

Best Regards

**Comment by ron190** [comment]
Thanks for this info.

It seems that Oracle is planning to remove JAXB with Java 11 so it's currently hidden in Java 9.
Try to run `java --add-modules java.xml.bind -jar jsql-injection-v0.81.jar` to enable the hidden package.

I will try to get rid of JAXB in the next release.

**Comment by dineshkumardk007** [comment]
sir i run that comment but it shows  :                                                                                                                        java --add-modules java.xml.bind -jar jsql-injection-v0.81.jar
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.xml.bind not found

**Comment by ron190** [comment]
Some are getting problems too though I'm running program v0.81 correctly on Java 9.0.4 (Windows) and Java 10.0.2 (Kali) but I haven't got enough precise info on the version of Java you are running to understand what's going on, see the issue #90372.

Also JAXB is not used anymore so `--add-modules java.xml.bind` is not required.

You can try to get the latest release too using command `sudo apt-get -f install jsql`, or make a system full upgrade with `apt update` then `apt full-upgrade`.
