### ISSUE TITLE
jsql-injection not working

### ISSUE THREAD

**Issue by Vdevv** [ron190/jsql-injection#90372]
jsql-injection (latest version) not working on the latest version of Kali Linux (2018.4) trying to open it from the menu but nothing happens.
Any help would be great.
Thanks.

**Comment by ron190** [comment]
Can you try to download and execute the latest version [jsql-injection-v0.81.jar](https://github.com/ron190/jsql-injection/releases/download/v0.81/jsql-injection-v0.81.jar) ?

**Comment by vingud** [comment]
i try executing the last version, and tried to execute it with an old version of java. 
This is the error mesage:
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.xml.bind not found

**Comment by Vdevv** [comment]
Same error to me as well.

**Comment by ron190** [comment]
Download the file jsql-injection-v0.81.jar then try to run the .jar with this command:

`java --add-modules java.xml.bind -jar jsql-injection-v0.81.jar`

**Comment by Verifirs** [comment]
> Download the file jsql-injection-v0.81.jar then try to run the .jar with this command:
> 
> `java --add-modules java.xml.bind -jar jsql-injection-v0.81.jar`

I did this, and received 
`java.lang.module.FindException: Module java.xml.bind not found`

**Comment by ron190** [comment]
Which version of jSQL and Java are you using ?

**Comment by ron190** [comment]
I have just downloaded Kali 2018.4, no problem for me with jsql v0.81 on Java 10.0.2-amd64-en.
Please update or simply tell me your version of jsql and Java, thanks.

**Comment by dineshkumardk007** [comment]
Jsql version: 0.81 and Kali version : 11.0.1 Thanks sir

**Comment by ron190** [comment]
I suppose it's Java 11.0.1 instead of Kali 11.0.1.

I've never run Java 11 nor Java 10 so maybe there's a problem, I'll check this and will report soon.

**Comment by vingud** [comment]
i solve the problem!
searching on google i saw a post where explained how to see wich versions of java are installed on our systems.
i try to change the version of java which execute the javaVM and i changed it to version 10 with this command. `sudo update-alternatives --config java` (you have to choose the version that works for you) and PUUUUFFF. Problem fixed.

**Comment by dineshkumardk007** [comment]
@vingud Thanks man It's work now Thanks a LOT
