### ISSUE TITLE
Is this project maintained still?

### ISSUE THREAD

**Issue by q2dg** [ron190/jsql-injection#90376]
Last commit is from long time ago...
Thanks!

**Comment by q2dg** [comment]
Well, it seems answer is no

**Comment by ron190** [comment]
Asking the very same question on dozens of Github page just makes it pointless to authors to answer it, doesn't it?

**Comment by q2dg** [comment]
I'm a CS teacher. I'm asking this to be sure I teach the most suitable tools.
