### ISSUE TITLE
HOW TO UPDATE IN KALI LINUX?

### ISSUE THREAD

**Issue by ubed354311** [ron190/jsql-injection#95334]
## Steps to reproduce the problem

  1. ...
  2. ...

**Comment by ron190** [comment]
Installation [jsql-injection-v0.85.jar]

Install Java 11 or up to 17, then download the latest release and double-click on the file jsql-injection-v0.85.jar to launch the software.
You can also type java -jar jsql-injection-v0.85.jar in your terminal to start the program.
If you are using Kali Linux then get the latest release using command sudo apt-get -f install jsql, or make a system full upgrade with apt update then apt full-upgrade.
To run older version on Java 16+ use java --illegal-access=warn --add-exports java.base/sun.net.www.protocol.http=ALL-UNNAMED -jar jsql-injection-v0.84.jar.
