### ISSUE TITLE
display for java apps weird

### ISSUE THREAD

**Issue by konn-neko** [ron190/jsql-injection#95341]
## What's the expected behavior?

no display mess up

![image](https://files.catbox.moe/o9k542.png)

## What's the actual behavior?

 f*ckup on display

![image](https://user-images.githubusercontent.com/92604391/147575939-b0b33518-2dd4-418b-bf8a-4c2575cc2fc1.png)

![image](https://files.catbox.moe/hdthkr.png)

## Any other detailed information about the Issue?

this happens on another application, which I believe is java based too

## Steps to reproduce the problem

UNKNOWN

for me, it happens when I hover over elements that give a description, or click drop down menus

![image](https://files.catbox.moe/9qpy9r.gif)

also 
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
```

if ran via command line

**Comment by ron190** [comment]
I do not manage to reproduce using `jSQL v0.85` and `Oracle JDK 17.0.1-amd64-en` with Windows on low resolution screen.

As you state that it occurs on another app then issue could be related to some other factors:

- You use a less common JDK?
  - Try to test on last Oracle JDK 17.0.1
- You use a high resolution screen?
  - Try to enable highres with menu Windows / Appearance / New 4K Window
- Maybe related to OS

**Comment by konn-neko** [comment]
> I do not manage to reproduce using `jSQL v0.85` and `Oracle JDK 17.0.1-amd64-en` with Windows on low resolution screen.
> 
> As you state that it occurs on another app then issue could be related to some other factors:
> 
> * You use a less common JDK?
>   
>   * Try to test on last Oracle JDK 17.0.1
> * You use a high resolution screen?
>   
>   * Try to enable highres with menu Windows / Appearance / New 4K Window
> * Maybe related to OS

I am on the newest windows version without going into beta, jdk is newest. i just reinstalled both java and jdk, still happens

my laptop screen is 1920 x 1080

**Comment by ron190** [comment]
Thanks for all the details and screens and gif.

Regarded your laptop resolution it seems not related to res, so maybe it's on the OS side.

I'm on a much lower win version so I'll try to see on a free win10/win11 trial VM, and someone else with similar configuration could also try in the meantime.

**Comment by konn-neko** [comment]
> Thanks for all the details and screens and gif.
> 
> Regarded your laptop resolution it seems not related to res, so maybe it's on the OS side.
> 
> I'm on a much lower win version so I'll try to see on a free win10/win11 trial VM, and someone else with similar configuration could also try in the meantime.

Thank you for helping

May i know what os you run

**Comment by ron190** [comment]
Usually I test on old VM, same for other OS like Linux.
And I've just tested on laptop win10 enterprise on jdk17.0.1 without managing to reproduce.
I'm left with win11 VM to try to reproduce.

You could also try to test and reproduce on VMs too. Though knowing that another Java app is broken can indicate your jdk has a problem.

**Comment by konn-neko** [comment]
> Usually I test on old VM, same for other OS like Linux. And I've just tested on laptop win10 enterprise on jdk17.0.1 without managing to reproduce. I'm left with win11 VM to try to reproduce.
> 
> You could also try to test and reproduce on VMs too. Though knowing that another Java app is broken can indicate your jdk has a problem.

i figured out my problem

go figure its a GPU driver that needed update
