### ISSUE TITLE
Custom Payloads

### ISSUE THREAD

**Issue by mastercho** [ron190/jsql-injection#95342]
Just wonder if there is a way to put our own custom payloads to be checked with Jsql? Because payload check are very limited here and most of times its misses injection meanwhile there is real sqlinj.

**Comment by ron190** [comment]
Sure, you can customize payloads directly in the app either:

- by adapting the payloads for the target database like MySQL (Menu>Windows>SQL Engine)
- by tampering the SQL query globally (Menu>Preferences>Tampering)

### Customize SQL payload
<img src="https://raw.githubusercontent.com/ron190/jsql-injection/master/web/images/v0.82/sqlengine.png"  />

### Tamper script
<img src="https://raw.githubusercontent.com/ron190/jsql-injection/master/web/images/v0.82/tamper.png"  />

**Comment by mastercho** [comment]
I was meaning for specific payload for example site having time-based and payload is 

 `0'XOR(if(now()=sysdate(),sleep(6),0))XOR'Z`
 
 IN SQL Engine under Time based i see only AND and OR, how prefix and suffix is added to that is unclear, if you can give more light on that how i can achieve that payload which i give for example.
 
 I noticed also that when i click Load data and its timeout once would stop meanwhile on scan timeout doesn't stop scanning. Any remedy on that? I tried to increase timeout time to 60sec and lower threads to 5 but no success

**Comment by ron190** [comment]
Using your payload as an example, jSQL usually does not require suffix and it retreives each part of the query:

1. First it finds the injection character: `0'` in `0'XOR(if(n...`
2. Then it finds `AND` or `OR` (similar to finding `XOR`): `XOR` in `0'XOR(if(n...`
3. Then it finds the payload: `if(now()=sysdate(),sleep(6),0)` in `0'XOR(if(now()=sysdate(),sleep(6),0))XOR'Z`
4. Finally it uses an end comment to close the query: so it would be `--+-` in `0'XOR(if(now()=sysdate(),sleep(6),0))--+-`

So, to produce a payload like `0020021200' XOR(if(0+1=1,1,sleep(5)))XOR'Z-- -5VJL` then you can:

- Replace `or` by `XOR` in tab `OR mode`
- Add missing parenthesis `()` and `XOR'Z` to existing payload in tab `Time` like the following:
```
${boolean.mode}(if(
    ${test},
    1,
    sleep(${sleep_time})
))XOR'Z
```

You can also use Tampering to convert spaces if you know that spaces make the query to fail.

Here's a working Time payload with the related syntax:
![image](https://user-images.githubusercontent.com/1971480/148121385-4c9825cb-429f-44a6-9a82-2e9f1d0806ee.png)

**Comment by mastercho** [comment]
Thank you so much for giving light on tunnel to clear out more SQL Engine, hope you will also fix issue with the timeout on Load Data so won't fail time out just like on init scan
