### ISSUE TITLE
Sudo apt install jsql-injection not working

### ISSUE THREAD

**Issue by cyberhellcommunity** [ron190/jsql-injection#95379]
I tried using "sudo apt install jsql-injection" To install jsql just as I did months ago, but it seems not to work. Is there a fix this? And which Java version is prefarable; 18 or 11 ?

**Comment by ron190** [comment]
- > I tried using "sudo apt install jsql-injection" To install jsql just as I did months ago, but it seems not to work.

I suppose you're on Kali ; maybe your index is not up to date, so you should try the following commands to update the system (or give more details about the error message):

> If you are using Kali Linux then get the latest release using command `sudo apt-get -f install jsql`, or make a system full upgrade with `apt update` then `apt full-upgrade`.

- > which Java version is prefarable; 18 or 11?

All versions from 11 to 20 should work properly. I just checked on 20 and it works too.
