### ISSUE TITLE
String display exception

### ISSUE THREAD

**Issue by fairycn** [ron190/jsql-injection#95481]
Version
[jSQL Injection v0.91](https://github.com/ron190/jsql-injection/releases/tag/v0.91)
OS : Windows 11 Simplified Chinese system
![image](https://github.com/ron190/jsql-injection/assets/74580422/aed97cd8-76fa-42d2-a147-bcb72ed710bd)
 v0.9.0 Normal

**Comment by ron190** [comment]
@fairycn It should be fixed now in [v0.92](https://github.com/ron190/jsql-injection/releases/tag/v0.92).
