### ISSUE TITLE
No cookies 

### ISSUE THREAD

**Issue by HasuTapeKg** [ron190/jsql-injection#95533]
WHY I HEVE NOT COOKIES TEXTBOX ![RDT_20240218_1357255127926311390663581.jpg](https://github.com/ron190/jsql-injection/assets/160435884/359b23b9-af47-48cc-a775-483535bc4810)

**Comment by ron190** [comment]
@HasuTapeKg Cookies are set in header as you see in your screenshot.
Use the "textbox" header to set cookies.
